version: "3.7"

services:
  srtwhip:
    image: eyevinntechnology/srt-whip:v0.2.3
    ports:
      - "3000:3000"
      - "9000-9999:9000-9999/udp"
  shaka:
    image: google/shaka-packager:v2.5.1
    command: [ 
      "packager", 
      "in=udp://0.0.0.0:1234,stream=audio,init_segment=/dash/shaka_audio.mp4,segment_template=/dash/shaka_audio_$$Number$$.m4s",
      "in=udp://0.0.0.0:1234,stream=video,init_segment=/dash/shaka_video.mp4,segment_template=/dash/shaka_video_$$Number$$.m4s", 
      "--mpd_output", "/dash/manifest.mpd" 
    ]
    volumes:
      - media:/dash
  srtrecv:
    depends_on:
      - shaka
    image: howlowck/srt
    command: [ "./srt-live-transmit", "srt://:4141/?mode=listener", "udp://shaka:1234" ]
  webserver:
    image: ghcr.io/patrickdappollonio/docker-http-server:v2
    depends_on:
      - shaka
    command: [ "http-server", "-d", "/dash", "--cors" ]
    ports:
      - "8080:5000/tcp"
    volumes:
      - media:/dash
  mpdwhep:
    depends_on:
      - webserver
    image: eyevinntechnology/mpd-whep
    environment:
      - MPD=http://webserver:8080/manifest.mpd
      - WHEP=http://localhost:8300/channel/srt
    ports:
      - "8000:8000/tcp"
  sfu:
    image: eyevinntechnology/wrtc-sfu:v0.4.0
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
    environment:
      - HTTP_PORT=8280
      - UDP_PORT=13000
      - IPV4_ADDR=127.0.0.1
      - API_KEY=example
    logging:
      driver: "local"
      options:
        max-size: 10m
    ports:
      - "8280:8280/tcp"
      - "13000:13000/udp"
  ingest:
    image: eyevinntechnology/wrtc-origin:v0.4.0
    depends_on:
      - sfu
      - sfu-edge
    environment:
      - PORT=8200
      - EXT_PORT=8200
      - ORIGIN_SFU_URL=http://sfu:8280/conferences/
      - SFU_API_KEY=example
      - EDGE_LIST_CONFIG=/etc/edge-list-config.json
      - HOSTNAME=${ORIGIN_HOST:-localhost}
    ports:
      - "8200:8200/tcp"
    extra_hosts:
      - egress:host-gateway
  sfu-edge:
    image: eyevinntechnology/wrtc-sfu:v0.4.0
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
    environment:
      - HTTP_PORT=8380
      - UDP_PORT=12000
      - IPV4_ADDR=127.0.0.1
      - API_KEY=example
    logging:
      driver: "local"
      options:
        max-size: 10m
    ports:
      - "8380:8380/tcp"
      - "12000:12000/udp"
  egress:
    image: eyevinntechnology/wrtc-whep:v0.1.2
    environment:
      - PORT=8300
      - EXT_PORT=8300
      - HOSTNAME=localhost
      - SMB_URL=http://sfu-edge:8380/conferences/
      - SMB_API_KEY=example
    ports:
      - "8300:8300/tcp"

volumes:
  media:
